### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by JaneSullivan-NOAA** [afsc-gap-products/akfishcondition#62]
### Issue Description
Hi Sean,
Working on the sablefish condition indicator. I'm getting the following error with the new release:
```
Error in calc_lw_residuals(len = sable_sub$length[sable_sub$species_code ==  : 
  object 'outlier.rm' not found
```
### Steps to Reproduce
I don't think a reprex is needed here. 

Steps to fix:

1. Change outlier.rm to outlier_rm on [L60](https://github.com/afsc-gap-products/akfishcondition/blob/2c30c4056255b39625d9ed4f2cdb3b8566980103/R/calc_lw_residuals.R#L60)
2. Once that's fixed, there will be a similar error for bias.correction on [L73](https://github.com/afsc-gap-products/akfishcondition/blob/2c30c4056255b39625d9ed4f2cdb3b8566980103/R/calc_lw_residuals.R#L73)
3. The roxygen dox needs to be updated for both of these params.

Thank you so much for all you do! You rock.

**Comment by sean-rohan-NOAA** [comment]
Thanks for bringing this to my attention, Jane. This should now be fixed by #63.

I really need to implement better tests and clean the documentation up.
